sonar.organization=areesha06
sonar.projectKey=Areesha06_cohort-9-mern-14267-areesha

sonar.sources=aninotes/backend/src,aninotes/backend/server.js,aninotes/frontend/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/*.test.js,aninotes/backend/tests/**

sonar.javascript.lcov.reportPaths=aninotes/backend/coverage/lcov.info,aninotes/frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
